# Generated by Django 3.0.5 on 2020-08-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_profile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
